#!/bin/sh

case $1 in
	1) pactl set-sink-volume @DEFAULT_SINK@ -10% && pkill -35 dwmblocks ;;
	2) pactl set-sink-mute @DEFAULT_SINK@ toggle && pkill -35 dwmblocks ;;
	3) pactl set-sink-volume @DEFAULT_SINK@ +10% && pkill -35 dwmblocks ;;
esac
